### ISSUE TITLE
Cannot join ARK Modding discord or send email via form

### ISSUE THREAD

**Issue by mle-ii** [ARKModding/site#12]
I'm pretty sure I'm doing things right, tried to contact via the form on your website but even that form seems to not do anything when I click send.  This is the message I tried to send.

Something seems broken with getting into the discord.  I think steam might have changed the games visibility.  I have it set like the instructions mention above yet I cannot see the games unless I am signed in.  I see that for my daughter her games don't even show up on the list so I do think I have the setting right as the link shows up but clicking on it requires a sign in.

Settings:
![image](https://github.com/ARKModding/site/assets/3632026/5c367169-3e92-4454-99e3-b301a8da4aaf)
You can see the link here when incognito:
![image](https://github.com/ARKModding/site/assets/3632026/84a8ac11-887c-49f3-8e1d-8129963c510a)
Clicking it takes you here:
![image](https://github.com/ARKModding/site/assets/3632026/74d3db13-40c4-4d01-8dae-b0e3705221d0)

**Comment by diannasandora** [comment]
I am having the same issue, I have tried to connect repeatedly prior to ASA release and I am still having this issue afterward. I would love to know what to do.

**Comment by mle-ii** [comment]
I was finally able to get in.  I used an incognito session and I also set "Inventory" and "Can post comments on my profile" to public as well.  Maybe it caused something in a cache to get uncached, or maybe there was a session cookie that was causing the connection to not work.
